 
  {$REGION 'SDL_InitFlags'}
operator in (const Left: SDL_InitFlag; const Right: SDL_InitFlags): Boolean; inline;
operator or (const Left: SDL_InitFlag; const Right: SDL_InitFlag): SDL_InitFlags; inline;
operator or (const Left: SDL_InitFlag; const Right: SDL_InitFlags): SDL_InitFlags; inline;
operator or (const Left: SDL_InitFlags; const Right: SDL_InitFlag): SDL_InitFlags; inline;
operator = (const Left: SDL_InitFlags; const Right: SDL_InitFlag): Boolean; inline;
operator = (const Left: SDL_InitFlag; const Right: SDL_InitFlags): Boolean; inline;
operator = (const Left: SDL_InitFlags; const Right: SDL_InitFlags): Boolean; inline;
operator <> (const Left: SDL_InitFlags; const Right: SDL_InitFlag): Boolean; inline;
operator <> (const Left: SDL_InitFlag; const Right: SDL_InitFlags): Boolean; inline;
operator <> (const Left: SDL_InitFlags; const Right: SDL_InitFlags): Boolean; inline;
operator + (const Left: SDL_InitFlags; const Right: SDL_InitFlag): SDL_InitFlags; inline;
operator + (const Left: SDL_InitFlags; const Right: SDL_InitFlags): SDL_InitFlags; inline;
operator - (const Left: SDL_InitFlags; const Right: SDL_InitFlag): SDL_InitFlags; inline;
operator := (const Value: SDL_InitFlag): SDL_InitFlags; inline;
operator := (const Value: SDL_InitFlag): String; inline;
operator := (const Value: SDL_InitFlags): String; inline;
  {$ENDREGION}
 
  {$REGION 'SDL_WindowFlags'}
operator in (const Left: SDL_WindowFlag; const Right: SDL_WindowFlags): Boolean; inline;
operator or (const Left: SDL_WindowFlag; const Right: SDL_WindowFlag): SDL_WindowFlags; inline;
operator or (const Left: SDL_WindowFlag; const Right: SDL_WindowFlags): SDL_WindowFlags; inline;
operator or (const Left: SDL_WindowFlags; const Right: SDL_WindowFlag): SDL_WindowFlags; inline;
operator = (const Left: SDL_WindowFlags; const Right: SDL_WindowFlag): Boolean; inline;
operator = (const Left: SDL_WindowFlag; const Right: SDL_WindowFlags): Boolean; inline;
operator = (const Left: SDL_WindowFlags; const Right: SDL_WindowFlags): Boolean; inline;
operator <> (const Left: SDL_WindowFlags; const Right: SDL_WindowFlag): Boolean; inline;
operator <> (const Left: SDL_WindowFlag; const Right: SDL_WindowFlags): Boolean; inline;
operator <> (const Left: SDL_WindowFlags; const Right: SDL_WindowFlags): Boolean; inline;
operator + (const Left: SDL_WindowFlags; const Right: SDL_WindowFlag): SDL_WindowFlags; inline;
operator + (const Left: SDL_WindowFlags; const Right: SDL_WindowFlags): SDL_WindowFlags; inline;
operator - (const Left: SDL_WindowFlags; const Right: SDL_WindowFlag): SDL_WindowFlags; inline;
operator := (const Value: SDL_WindowFlag): SDL_WindowFlags; inline;
operator := (const Value: SDL_WindowFlag): String; inline;
operator := (const Value: SDL_WindowFlags): String; inline;
  {$ENDREGION}
 
  {$REGION 'SDL_Surface_Flags'}
operator in (const Left: SDL_Surface_Flag; const Right: SDL_Surface_Flags): Boolean; inline;
operator or (const Left: SDL_Surface_Flag; const Right: SDL_Surface_Flag): SDL_Surface_Flags; inline;
operator or (const Left: SDL_Surface_Flag; const Right: SDL_Surface_Flags): SDL_Surface_Flags; inline;
operator or (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flag): SDL_Surface_Flags; inline;
operator = (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flag): Boolean; inline;
operator = (const Left: SDL_Surface_Flag; const Right: SDL_Surface_Flags): Boolean; inline;
operator = (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flags): Boolean; inline;
operator <> (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flag): Boolean; inline;
operator <> (const Left: SDL_Surface_Flag; const Right: SDL_Surface_Flags): Boolean; inline;
operator <> (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flags): Boolean; inline;
operator + (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flag): SDL_Surface_Flags; inline;
operator + (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flags): SDL_Surface_Flags; inline;
operator - (const Left: SDL_Surface_Flags; const Right: SDL_Surface_Flag): SDL_Surface_Flags; inline;
operator := (const Value: SDL_Surface_Flag): SDL_Surface_Flags; inline;
operator := (const Value: SDL_Surface_Flag): String; inline;
operator := (const Value: SDL_Surface_Flags): String; inline;
  {$ENDREGION}
 
  {$REGION 'SDL_Keymods'}
operator in (const Left: SDL_Keymod; const Right: SDL_Keymods): Boolean; inline;
operator or (const Left: SDL_Keymod; const Right: SDL_Keymod): SDL_Keymods; inline;
operator or (const Left: SDL_Keymod; const Right: SDL_Keymods): SDL_Keymods; inline;
operator or (const Left: SDL_Keymods; const Right: SDL_Keymod): SDL_Keymods; inline;
operator = (const Left: SDL_Keymods; const Right: SDL_Keymod): Boolean; inline;
operator = (const Left: SDL_Keymod; const Right: SDL_Keymods): Boolean; inline;
operator = (const Left: SDL_Keymods; const Right: SDL_Keymods): Boolean; inline;
operator <> (const Left: SDL_Keymods; const Right: SDL_Keymod): Boolean; inline;
operator <> (const Left: SDL_Keymod; const Right: SDL_Keymods): Boolean; inline;
operator <> (const Left: SDL_Keymods; const Right: SDL_Keymods): Boolean; inline;
operator + (const Left: SDL_Keymods; const Right: SDL_Keymod): SDL_Keymods; inline;
operator + (const Left: SDL_Keymods; const Right: SDL_Keymods): SDL_Keymods; inline;
operator - (const Left: SDL_Keymods; const Right: SDL_Keymod): SDL_Keymods; inline;
operator := (const Value: SDL_Keymod): SDL_Keymods; inline;
operator := (const Value: SDL_Keymod): String; inline;
operator := (const Value: SDL_Keymods): String; inline;
  {$ENDREGION}
 
  {$REGION 'SDL_EventTypes'}
operator in (const Left: SDL_EventType; const Right: SDL_EventTypes): Boolean; inline;
operator or (const Left: SDL_EventType; const Right: SDL_EventType): SDL_EventTypes; inline;
operator or (const Left: SDL_EventType; const Right: SDL_EventTypes): SDL_EventTypes; inline;
operator or (const Left: SDL_EventTypes; const Right: SDL_EventType): SDL_EventTypes; inline;
operator = (const Left: SDL_EventTypes; const Right: SDL_EventType): Boolean; inline;
operator = (const Left: SDL_EventType; const Right: SDL_EventTypes): Boolean; inline;
operator = (const Left: SDL_EventTypes; const Right: SDL_EventTypes): Boolean; inline;
operator <> (const Left: SDL_EventTypes; const Right: SDL_EventType): Boolean; inline;
operator <> (const Left: SDL_EventType; const Right: SDL_EventTypes): Boolean; inline;
operator <> (const Left: SDL_EventTypes; const Right: SDL_EventTypes): Boolean; inline;
operator + (const Left: SDL_EventTypes; const Right: SDL_EventType): SDL_EventTypes; inline;
operator + (const Left: SDL_EventTypes; const Right: SDL_EventTypes): SDL_EventTypes; inline;
operator - (const Left: SDL_EventTypes; const Right: SDL_EventType): SDL_EventTypes; inline;
operator := (const Value: SDL_EventType): SDL_EventTypes; inline;
operator := (const Value: SDL_EventType): String; inline;
operator := (const Value: SDL_EventTypes): String; inline;
  {$ENDREGION}
 
  {$REGION 'SDL_RendererFlags'}
operator in (const Left: SDL_RendererFlag; const Right: SDL_RendererFlags): Boolean; inline;
operator or (const Left: SDL_RendererFlag; const Right: SDL_RendererFlag): SDL_RendererFlags; inline;
operator or (const Left: SDL_RendererFlag; const Right: SDL_RendererFlags): SDL_RendererFlags; inline;
operator or (const Left: SDL_RendererFlags; const Right: SDL_RendererFlag): SDL_RendererFlags; inline;
operator = (const Left: SDL_RendererFlags; const Right: SDL_RendererFlag): Boolean; inline;
operator = (const Left: SDL_RendererFlag; const Right: SDL_RendererFlags): Boolean; inline;
operator = (const Left: SDL_RendererFlags; const Right: SDL_RendererFlags): Boolean; inline;
operator <> (const Left: SDL_RendererFlags; const Right: SDL_RendererFlag): Boolean; inline;
operator <> (const Left: SDL_RendererFlag; const Right: SDL_RendererFlags): Boolean; inline;
operator <> (const Left: SDL_RendererFlags; const Right: SDL_RendererFlags): Boolean; inline;
operator + (const Left: SDL_RendererFlags; const Right: SDL_RendererFlag): SDL_RendererFlags; inline;
operator + (const Left: SDL_RendererFlags; const Right: SDL_RendererFlags): SDL_RendererFlags; inline;
operator - (const Left: SDL_RendererFlags; const Right: SDL_RendererFlag): SDL_RendererFlags; inline;
operator := (const Value: SDL_RendererFlag): SDL_RendererFlags; inline;
operator := (const Value: SDL_RendererFlag): String; inline;
operator := (const Value: SDL_RendererFlags): String; inline;
  {$ENDREGION}
  {$REGION 'SDL_ButtonEnum'}
operator := (const Value: SDL_ButtonEnum): String; inline;
operator + (const Left: SDL_ButtonEnum; const Right: String): String; inline;
operator + (const Left: String; const Right: SDL_ButtonEnum): String; inline;
operator + (const Left: SDL_ButtonEnum; const Right: Char): String; inline;
operator + (const Left: Char; const Right: SDL_ButtonEnum): String; inline;
  {$ENDREGION}
  {$REGION 'SDL_SwapInterval'}
operator := (const Value: SDL_SwapInterval): String; inline;
operator + (const Left: SDL_SwapInterval; const Right: String): String; inline;
operator + (const Left: String; const Right: SDL_SwapInterval): String; inline;
operator + (const Left: SDL_SwapInterval; const Right: Char): String; inline;
operator + (const Left: Char; const Right: SDL_SwapInterval): String; inline;
  {$ENDREGION}
  {$REGION 'SDL_Bool'}
operator := (const Value: SDL_Bool): String; inline;
operator + (const Left: SDL_Bool; const Right: String): String; inline;
operator + (const Left: String; const Right: SDL_Bool): String; inline;
operator + (const Left: SDL_Bool; const Right: Char): String; inline;
operator + (const Left: Char; const Right: SDL_Bool): String; inline;
  {$ENDREGION}
  {$REGION 'SDL_LogPriority'}
operator := (const Value: SDL_LogPriority): String; inline;
operator + (const Left: SDL_LogPriority; const Right: String): String; inline;
operator + (const Left: String; const Right: SDL_LogPriority): String; inline;
operator + (const Left: SDL_LogPriority; const Right: Char): String; inline;
operator + (const Left: Char; const Right: SDL_LogPriority): String; inline;
  {$ENDREGION}
  {$REGION 'SDL_LogCategory'}
operator := (const Value: SDL_LogCategory): String; inline;
operator + (const Left: SDL_LogCategory; const Right: String): String; inline;
operator + (const Left: String; const Right: SDL_LogCategory): String; inline;
operator + (const Left: SDL_LogCategory; const Right: Char): String; inline;
operator + (const Left: Char; const Right: SDL_LogCategory): String; inline;
  {$ENDREGION}
  {$REGION 'SDL_EventState'}
operator := (const Value: SDL_EventState): String; inline;
operator + (const Left: SDL_EventState; const Right: String): String; inline;
operator + (const Left: String; const Right: SDL_EventState): String; inline;
operator + (const Left: SDL_EventState; const Right: Char): String; inline;
operator + (const Left: Char; const Right: SDL_EventState): String; inline;
  {$ENDREGION}
  {$REGION 'SDL_AudioFormat'}
operator := (const Value: SDL_AudioFormat): String; inline;
operator + (const Left: SDL_AudioFormat; const Right: String): String; inline;
operator + (const Left: String; const Right: SDL_AudioFormat): String; inline;
operator + (const Left: SDL_AudioFormat; const Right: Char): String; inline;
operator + (const Left: Char; const Right: SDL_AudioFormat): String; inline;
  {$ENDREGION}
