 
  {$REGION 'GL_ClearBufferTypes'}
operator in (const Left: GL_ClearBufferType; const Right: GL_ClearBufferTypes): Boolean; inline;
operator or (const Left: GL_ClearBufferType; const Right: GL_ClearBufferType): GL_ClearBufferTypes; inline;
operator or (const Left: GL_ClearBufferType; const Right: GL_ClearBufferTypes): GL_ClearBufferTypes; inline;
operator or (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferType): GL_ClearBufferTypes; inline;
operator = (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferType): Boolean; inline;
operator = (const Left: GL_ClearBufferType; const Right: GL_ClearBufferTypes): Boolean; inline;
operator = (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferTypes): Boolean; inline;
operator <> (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferType): Boolean; inline;
operator <> (const Left: GL_ClearBufferType; const Right: GL_ClearBufferTypes): Boolean; inline;
operator <> (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferTypes): Boolean; inline;
operator + (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferType): GL_ClearBufferTypes; inline;
operator + (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferTypes): GL_ClearBufferTypes; inline;
operator - (const Left: GL_ClearBufferTypes; const Right: GL_ClearBufferType): GL_ClearBufferTypes; inline;
operator := (const Value: GL_ClearBufferType): GL_ClearBufferTypes; inline;
operator := (const Value: GL_ClearBufferType): String; inline;
operator := (const Value: GL_ClearBufferTypes): String; inline;
  {$ENDREGION}
